# Local variables
@operator_id = 6413780642fbcb5f9b80fb5c
@companyId = 6413406342fbcb5f9b80fb5a
@dosimeterId = bdca535261245abfcd11aea3

### Obtener todos los films
GET http://localhost:8000/film/by_company/{{companyId}}

### Obtener todos los films de un periodo
GET http://localhost:8000/film/by_company/{{companyId}}?period=202304

### Obtener un operador por su Id

GET http://localhost:8000/film/629549627ce585bd5d33124b

### Crear un operador nuevo

# @name createFilm
POST http://localhost:8000/film
content-type: application/json

{
  "company_id": "{{companyId}}",
  "operator_id": "{{operator_id}}",
  "company_code": "123456",
  "period": "64175e394eb8b9e0aaff082d",
  "status": "Enabled"
}

### Actualizar un film
@lastFilmId = {{createFilm.response.body.$._id}}
POST http://localhost:8000/film
content-type: application/json

{
  "_id": {{lastFilmId}},
  "company_id": "{{companyId}}",
  "operator_id": "{{operator_id}}",
  "company_code": "123456",
  "period": "202001",
  "status": "InUse"
}



###

