# Local variables
// La idea sería obtener referencias de los empleados que 
//se fueron creando en otros test

@operator_id = 62eeb7ec0c11652e03b5e6b7
@dose= 456.0
@when=2022-12-31T03:00:00.000Z
@company_id = 62eca328d27242b672f375f3
@dosimeter_id = bdca535261245abfcd11aea3
@period_id = 631fbae2a38db0d5d29ac2b5
@film_id = 6316705ac265ae52d4d64717


### REQUESTS

### Obtener dosis de films
GET http://localhost:8000/film_dose/{{company_id}}/{{operator_id}}

### Cargar una nueva dosis

# @name create Film Doses
POST http://localhost:8000/film_dose
content-type: application/json

{   
    "company_id": "{{company_id}}",
    "operator_id": "{{operator_id}}",
    "film_id": "{{film_id}}",
    "dose": 1.55,
    "period_id": "{{period_id}}"
    
}

###
POST http://localhost:8000/film_dose
content-type: application/json

{
"_id": "6425f07af245dec56f0a4f73",
"company_id": "6425a424f245dec56f0a4f48",
"period_id": "6425b8f4f245dec56f0a4f4c",
"operator_id": "6425b8bbf245dec56f0a4f4a",
"film_id": "6425c92ff245dec56f0a4f4e",
"dose": 12301
}

###

GET http://localhost:8000/operators/overdose/abca535261245abfcd4da31a
