# Local variables
@companyId = 6425a424f245dec56f0a4f48
@dosimeterId = bdca535261245abfcd11aea3
@periodId = 6425b8f4f245dec56f0a4f4c

###

GET http://localhost:8000/operators/doses/{{companyId}}/{{periodId}}

### Obtener todos los operators
GET http://localhost:8000/operators/{{companyId}}

### Obtener un operador por su Id

GET http://localhost:8000/operator/62681c48726191810ba5ae6a

### Crear un operador nuevo

# @name createOperator
POST http://localhost:8000/operator
content-type: application/json

{
  "company_id": "{{companyId}}",
  "name": "gonzalo",
  "dni": "09876543210",
  "licence": "221312-213412-222",

  "status": "Enabled"
}


### Actualizar un operator
@lastUserId = {{createOperator.response.body.$._id}}
POST http://localhost:8000/operator
content-type: application/json

{
  "_id": {{lastUserId}},
  "company_id": "{{companyId}}",
  "name": "gonzalo",
  "dni": "09876543210",
  "licence": "221312-213412-222",
  "dosimeter_id": "{{dosimeterId}}",
  "status": "Enabled"

}

###

DELETE http://localhost:8000/operator/62691c48726191810ba5ae6a