# Local variables
@companyId = "abca535261245abfcd4da31a"

### REQUESTS

### Obtener todos los usuarios
GET http://localhost:8000/users/62eca328d27242b672f375f3

###
GET http://localhost:3000/user/email/pablushka@gmail.com/'

### Obtener un usuario por su Id
GET http://localhost:8000/user/6265e9645df68091cc16c6bc

### Crear un usuario nuevo

# @name createUser
POST http://localhost:8000/user
content-type: application/json

{
  "name": "Pablo",
  "last_name": "Centurion",
  "company_id": {{companyId}},
  "role": "Admin",
  "status": "Enabled"
}

###

@lastUserId = {{createUser.response.body.$._id}}

### Actualizar un usuario
POST http://localhost:8000/user
content-type: application/json

{
  "_id": "62e2ddf29cb273161249e4e4",
  "name": "Pablo",
  "last_name": "C.",
  "email": "pcenturion@nuclearis.com",
  "company_id": "abca535261245abfcd4da31a",
  "role": "Admin",
  "status": "Enabled"
}

### Buscar usuario por email
GET http://localhost:8000/user/email/pcenturion@nuclearis.com

### Eliminar un usuario
DELETE http://localhost:8000/user/6266bbe138a6e948659d5f4c

